### ISSUE TITLE
gpu scaling filter broken

### ISSUE THREAD

**Issue by genevera** [ProjectMoon/open-webui-filters#1]
Since open-webui removed CHROMA_CLIENT from config, this doesn't work anymore.

**Comment by ProjectMoon** [comment]
Thanks for the issue. This is indeed true. There was a similar problem with the memory filter. However in the case of the GPU scaling filter, I am thinking of deprecating it because you can adjust num_gpu in chat controls now. I originally made it because the parameter couldn't be adjusted in older versions.

**Comment by genevera** [comment]
True though this does that automatically as needed per turn in the convo which is really nice for those of us doing double and triple duty on smaller GPUs!

**Comment by ProjectMoon** [comment]
Please let me know if the latest version (0.2.1) of the filter works.

**Comment by genevera** [comment]
Unfortunately it does not work:

```
open-webui  | No requirements found in frontmatter.
open-webui  | Error loading module: gpu_scaling_filter: No module named 'open_webui.apps.rag'
open-webui  | No module named 'open_webui.apps.rag'
open-webui  | INFO:     192.168.1.117:0 - "POST /api/v1/functions/create HTTP/1.1" 400Bad Request
```

This is the error I get trying to install it.

**Comment by ProjectMoon** [comment]
I fixed the imports this time (I think). Can you try it again? I also updated the checkpoint filter.

**Comment by ProjectMoon** [comment]
Going to close this as fixed. Reopen if there are still problems.
